### ISSUE TITLE
Broken window when running on Linux aarch64 with Wayland Labwc

### ISSUE THREAD

**Issue by qrp73** [johnfactotum/foliate#1499]
When launching the application on Linux aarch64 with the Wayland compositor Labwc, the window content is corrupted – random pixels are displayed and moving. If you find the window border with the mouse and resize it after startup, the content is corrected.

## Steps to reproduce

1) Install app: ```sudo apt install foliate```
2) Start app

### Expected behavior

The application starts with the window content displayed correctly

### Actual behavior

![Image](https://github.com/user-attachments/assets/6cef488b-2031-4e6c-a64f-1152fab2a5e7)

## Version

OS: Raspberry Pi OS Bookworm with Wayland Labwc compositor

Installed with ```sudo apt install foliate```

```
$ foliate --version
2.6.4

$ uname -a
Linux raspi 6.6.74+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.74-1+rpt1 (2025-01-27) aarch64 GNU/Linux

$ echo $XDG_CURRENT_DESKTOP
labwc:wlroots

$ labwc --version
labwc 0.8.1

$ glxinfo | grep "OpenGL version"
OpenGL version string: 3.1 Mesa 24.2.8-1~bpo12+rpt2
```

### Console output:
```
$ foliate 

** (WebKitWebProcess:2): WARNING **: 10:13:08.460: Can't connect to a11y bus: Could not connect: No such file or directory

(com.github.johnfactotum.Foliate:54348): Gjs-WARNING **: 10:13:09.892: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  @/usr/bin/foliate:9:17
```

### Test ebook which can be used to reproduce the issue

Unzip and open:
[test.epub.zip](https://github.com/user-attachments/files/19385396/test.epub.zip)

**Comment by johnfactotum** [comment]
Definitely not our bug.

**Comment by qrp73** [comment]
this issue is unique, it is reproduced in this reader and https://babluboy.github.io/bookworm/ reader. I didn't seen such bug in other apps. Bookworm reader also fails with segmetation fault on every attempt to click almost any menu item.

Foliate works more stable, menu works, but it opens with corrupted window. When I resize window, its content is corrected, but when I open Library and open another book, the window content is corrupted again.

I think this is due to some mistake or specific code in the Foliate code which cause rendering issue on Wayland compositors. Maybe something like non-POT texture size or something like that.

Update: It is interesting to note that sometimes the application starts with a normal window, and sometimes with a corrupted one, meaning the bug is floating.

**Comment by johnfactotum** [comment]
It's most likely an issue with WebKitGTK, GTK, or some other component, as Foliate does not have any low level code for drawing the window or its contents.

At any rate, v2 is not supported anymore.

**Comment by archisman-panigrahi** [comment]
@qrp73 Does the bug persist when you install version 3 (e.g. with flatpak)?

**Comment by qrp73** [comment]
> Does the bug persist when you install version 3 (e.g. with flatpak)?

I don't use flatpak, only apt. With all latest updates the issue still present. 
As discovered by @cillian64 [here](https://github.com/labwc/labwc/issues/2634), the issue happens in WebKitGTK apps:
```
I can also reproduce this in epiphany (which also uses webkitgtk).

Adding some debugging in wlroots, it looks like what happens is:

    App starts up correctly using ARGB SHM bufs, looks correct
    App receives linux-dmabuf feedback
    App creates some linux-dmabuf buffers with the Broadcom UIF modifier, but it doesn't actually display these (by attaching them to a surface and committing). The old SHM buffers remain displayed.
    The contents of the SHM buffers gets replaced with UIF content. We render this UIF content as though it was linear and that's why the output looks corrupt
    If you resize the window then the app attaches/commits its linux-dmabuf buffers. These correctly have UIF set in their modifiers attribute so we render them correctly.

This really sounds like it's a webkitgtk bug. However, if so it should be reproducible in other compositors and I don't see the problem in Weston. So a bit more debugging might be necessary first
```

The suggested solution with WEBKIT_DISABLE_COMPOSITING_MODE=1 works for me. 

As a solution I created this ```foliate-fix``` shell script in ```/usr/local/bin/``` folder:
```
#!/usr/bin/env bash

WEBKIT_DISABLE_COMPOSITING_MODE=1 foliate "$@"
```

And now I can run app with ```foliate-fix``` command and it starts with no issue.

In order to start it from start menu in labwc wf-panel-pi, I created ```user-foliate.desktop``` shorcut in ```~/.local/share/applications/``` folder with the following content:
```
[Desktop Entry]
Name=Foliate Fix
Exec=/usr/local/bin/foliate-fix
Comment=View eBooks
Terminal=false
Icon=com.github.johnfactotum.Foliate
Type=Application
Categories=Office;Viewer;
MimeType=application/epub+zip;application/x-mobipocket-ebook;application/vnd.amazon.mobi8-ebook;application/x-fictionbook+xml;application/x-zip-compressed-fb2;application/vnd.comicbook+zip;application/vnd.comicbook-rar;application/x-cb7;application/x-cbt;x-scheme-handler/opds;
Keywords=Ebook;Book;EPUB;Viewer;Reader;
Actions=new-window;
```

Now I can start it from start menu as ```Foliate Fix``` app and it starts with no issue

**Comment by archisman-panigrahi** [comment]
Given it is not a foliate bug (generic webkit bug), and a workaround exists, the issue can be closed.

**Comment by qrp73** [comment]
ok, since it looks like some general WebKitGTK or compositor bug I will close this issue. In case if the root of cause is within app, you can re-open it or open a new issue and link this one.
